### ISSUE TITLE
Allow local config file

### ISSUE THREAD

**Issue by xi** [BenBrock/reple#4]
There are two ways to provide a config file: Using the the `-env foo` and `-f foo.json` arguments. I feel this is redundant as they are basically the same.

Instead, I would expect `-f foo.json` to read a local file. I would also expect `-f /home/user/foo.json` to work.

**Comment by BenBrock** [comment]
They're different.  `-f` accepts a path to a json config file, which could be custom.  On the other hand, `-env` accepts the name of a particular language (not a json file) which is supported by reple.
