### ISSUE TITLE
Request: Allow free functions in c++

### ISSUE THREAD

**Issue by henrik-jensen** [BenBrock/reple#7]
As all the code is encapsulated in `main()`, free functions are not possible (though classes are).
A workaround is of course the following:
```c++
$ reple -env cxx
> struct FreeFuncs {
>   static void do_stuff() {
>     std::cout << "Hello from do_stuff" << std::endl;
>   }
> };
> FreeFuncs::do_stuff();
Hello from do_stuff
>
```
or:
```c++
> struct {
>   void operator()() {
>    std::cout << "Hello from do_stuff" << std::endl;
>   }
> } do_stuff;
> do_stuff();
Hello from do_stuff
>
```
even:
```c++
> struct { int operator()(int a, int b) { return a+b;} } add;
> std::cout << add( 1, 3) << "\n";
4
>
```
but that is some weird and annoying boilerplate just to write a function.

It would be nice if the way to write your `reple` code mimics your usual c++ style.
I know it's a nice to have but are there any easy solution to this in the python code?

**Comment by BenBrock** [comment]
If I understand your request correctly, this is already supported.  The character `$` can be used to mark code that should go in the "prolog," which in C++ is before the `main` function.

```c++
xiii@marybeth:~/src/thesis$ reple -env cxx
> $struct foo {
>   int x;
>   int y;
> };$
> foo f;
> f.x = 12;
>
```

**Comment by henrik-jensen** [comment]
Yeps, it works, great, thanks.
```c++
> $void MyFreeFunc() {
>   std::cout << "Free Func with prolog char $" << "\n";
> }$
> MyFreeFunc();
Free Func with prolog char $
>
```
@BenBrock - ~You can close the issue it if you want to.~ Oh you already did 👍
PS! And sorry, it is already in the documentation. An oversight from me.

**Comment by BenBrock** [comment]
No worries!  Glad to have your comments. :)
